# This file is required for running the API in VSC
spring:
  elasticsearch:
    rest:
      uris: "localhost:9200"

server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    keystore: classpath:certificate/localhost.p12
    key-store-password:

api:
  endpoint:
    service_search: "https://localhost:8443/dosapi/dosservices/v0.0.1/services/byfuzzysearch"

configuration:
  version: "v0.0.1"
  validation:
    min_search_term_length: 3
    max_search_criteria: 5
  search_parameters:
    max_num_services_to_return: 5
    fuzz_level: 0
    name_priority: 1
    address_priority: 0
    postcode_priority: 0
    public_name_priority: 0
