# This file is required for running the API via the make commands
spring:
  elasticsearch:
    rest:
      uris: ${ELASTICSEARCH_URL}

server:
  port: ${SERVER_PORT}

api:
  endpoint:
    service_search: ${API_SERVICE_SEARCH_ENDPOINT}

configuration:
  version: ${VERSION}
  validation:
    min_search_term_length: ${MIN_SEARCH_TERM_LENGTH}
    max_search_criteria: ${MAX_SEARCH_CRITERIA}
  search_parameters:
    max_num_services_to_return: ${MAX_NUM_SERVICES_TO_RETURN}
    fuzz_level: ${FUZZ_LEVEL}
    name_priority: ${NAME_PRIORITY}
    address_priority: ${ADDRESS_PRIORITY}
    postcode_priority: ${POSTCODE_PRIORITY}
    public_name_priority: ${PUBLIC_NAME_PRIORITY}
